name: Tests

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check if the repository is private
        run: exit 1
        if: ${{github.event.repository.private}}
      - name: Tests
        uses: Yandex-Practicum/test-project-action@v1
        with:
<<<<<<< HEAD
          project: '-tebe-nado-fd'
=======
          project: 'ono-tebe-nado-fd'
>>>>>>> da0323ffb9debcbc7eb9448b46a172c2886aa417
